import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import HeaderBar from "@/components/header-bar/header-bar";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Toaster position="top-center" richColors />
            <body className={inter.className} style={{"marginTop": "var(--header-bar-heigth)"}}>
                <HeaderBar/>
                {children}
            </body>
        </html>
    );
}
